INSERT INTO PRODUCT_METADATA (PRODUCT_ID, CATEGORY, BRAND)
VALUES ('MB-2093193398', 'Men', 'Adidas');
INSERT INTO PRODUCT_METADATA (PRODUCT_ID, CATEGORY, BRAND)
VALUES ('MD-543564697', 'Women', 'Nike');

INSERT INTO SHOPPER (SHOPPER_ID, NAME, ADDRESS)
VALUES ('S-1000', 'Shopper 1', 'Online');